// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniShoppingCartAPI.DbContexts;

#nullable disable

namespace MiniShoppingCartAPI.Migrations
{
    [DbContext(typeof(MiniShoppingCartApiContextSQLExpress))]
    [Migration("20240327054500_DB_Setup")]
    partial class DB_Setup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("MiniShoppingCartAPI.Entities.Cart", b =>
                {
                    b.Property<Guid>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SetQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("CartId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("MiniShoppingCartAPI.Entities.Product", b =>
                {
                    b.Property<Guid>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Productname")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Pid");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Pid = new Guid("49358d8c-437d-4cbb-955e-b9df3e115400"),
                            Price = 100,
                            Productname = "Apple",
                            Quantity = 10
                        },
                        new
                        {
                            Pid = new Guid("235a07e3-5c0c-48ca-a9e1-44a27ef0be6d"),
                            Price = 50,
                            Productname = "Orange",
                            Quantity = 20
                        },
                        new
                        {
                            Pid = new Guid("9ec0e6e7-31d3-45d3-abaa-ed4d167314a1"),
                            Price = 10,
                            Productname = "Banana",
                            Quantity = 50
                        },
                        new
                        {
                            Pid = new Guid("e4935e46-2cc1-4c12-8e76-e9ca64162a9d"),
                            Price = 200,
                            Productname = "Watermelon",
                            Quantity = 5
                        },
                        new
                        {
                            Pid = new Guid("3ac87c2d-6d88-4778-8f88-1aea9e3da21f"),
                            Price = 30,
                            Productname = "Strawberry",
                            Quantity = 100
                        });
                });

            modelBuilder.Entity("MiniShoppingCartAPI.Entities.User", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.HasKey("Uid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MiniShoppingCartAPI.Entities.Cart", b =>
                {
                    b.HasOne("MiniShoppingCartAPI.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniShoppingCartAPI.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
